### ISSUE TITLE
[Silent Hill 4] Artifacts on letters when importing a font

### ISSUE THREAD

**Issue by SlowpokeVG** [belek666/fontsh234#1]
Hello. 
When I'm trying to export letters from a font taken out of a fan translation file and insert them into an original English font file, weird artifacts appear on the bottom of every letter. 
Every letter looks fine in exported .tga, glitch only appears in the game itself.
How it should look:
![fantranslation font](https://user-images.githubusercontent.com/15838358/43101177-56f0ae3e-8ed0-11e8-8539-da47d496008e.jpg)
How it looks:
![imported font](https://user-images.githubusercontent.com/15838358/43101178-57180e0c-8ed0-11e8-9f19-80b2edc6378a.jpg)

Here are two font files, one of them is a font file that came with a fan translation and another is what your tool exported:
[fonts.zip](https://github.com/belek666/fontsh234/files/2220887/fonts.zip)

**Comment by belek666** [comment]
Hi
I forget that sh4 fonts have different height. Please check new commit and let me know if everything is fine.

**Comment by SlowpokeVG** [comment]
Thank you! That fixed it.
![photo_2018-07-25_11-35-08](https://user-images.githubusercontent.com/15838358/43189528-7411002e-8fff-11e8-893a-ab35a5cf4b6a.jpg)
