### ISSUE TITLE
Custom height (y) WITH custom width (x) for font replacements?

### ISSUE THREAD

**Issue by Polymega** [belek666/fontsh234#2]
@AeroWidescreen @elishacloud

Hi belek666, 

Thanks for getting in touch with me! Over the past year or two I've been collaborating with talented programmers and modders who have been making the PC version of Silent Hill 2 the best it can be:
https://github.com/elishacloud/Silent-Hill-2-Enhancements

You can see a sample of just some of the improvements here: 
https://www.youtube.com/watch?v=878F2cbLAXo 
(We will be releasing a new, updated trailer showcasing even more improvements to the game in the near future.) 

One of our future goals is to implement "Enhanced Fullscreen Images." The fullscreen images are things like the main menu, save screen, inventory screen, memos/riddles screens, and, of course, the fonts/subtitles. 

Your software, fontsh234, looks to be exactly what we need to hopefully implement "HD fonts" into SH2 PC in the future. However, in order to do this we'd need to be able to upload/replace the fonts at a higher resolution for both width and height. But we can only do custom width with your software, is that correct? 

If so, would there be anyway for you to modify your software to allow us to use fully custom-sized font files? I realize under normal circumstances this would probably crash the game but we are planning on finding the memory addresses/locations for these files in the PC game and calling our own memory addresses to allow us to use custom sized images. 

[We've actually recently done the same thing for the audio files for the game.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SfxPatch.cpp) The sddata.bin file's size is hard-coded into the executable but @elishacloud wrote a fix to bypass this restriction. So we'd be doing the same for the fullscreen images (which could include the font images). 

I'm looking forward to your thoughts on this! I've included @AeroWidescreen and @elishacloud on this conversation as they're the lead modder and programmer for the "Silent Hill 2: Enhanced Edition" project. 

Thanks again!

**Comment by belek666** [comment]
Hi
Wow! What a great project you are working on. 
I've checked again and it's possible to change font height in silent hill 2. Before font data there is header where are numbers related to font dimension, font data addresses, and pallete:

struct sh2_font_file_header
{
		std::uint16_t normalKFontWidth;  // 20 - not sure
		std::uint16_t normalFontHeight;   // 30
		std::uint16_t smallKFontWidth; // 16 - not sure
		std::uint16_t smallFontHeight;  // 24
		std::uint32_t normalFontOffset;  // character height = 30
		std::uint32_t smallFontOffset;   // character height = 24
		std::uint8_t  pallete[7];
		std::uint8_t  unk;
};

Pallete is always: 00 5F 7F 9F BF DF FF so it easy to find those values in hex editor. I'm not sure if changing font height is what you want - in-game letters get bigger but without proper scaling.

**Comment by AeroWidescreen** [comment]
Hi belek666, thank you for your help with this!

> I'm not sure if changing font height is what you want - in-game letters get bigger but without proper scaling.

We had to [fix the scaling](https://github.com/ThirteenAG/WidescreenFixesPack/issues/375#issuecomment-379610900) when increasing the resolution of the main menu background too. We should be able to do the same for the font with a little bit of research. 😀

**Comment by belek666** [comment]
@Polymega @AeroWidescreen 
Hey
I'd managed to implement loading fonts from a tga file (width data is used from exe). Not sure if it's the correct way of doing it. I have zero experience with driectx library. Fonts can be scaled - tested 4400x9600 resolution. What do you think? Can it be usable in the Silent-Hill-2-Enhancements project?
[Release.zip](https://github.com/belek666/fontsh234/files/2752256/Release.zip)

**Comment by AeroWidescreen** [comment]
Apologies, but I'm not sure if this is working for me or not. The tga file I saved using Photoshop doesn't seem to do anything. I think you said there was a specific image editing software you had to use, but I forgot the name of it.

**Comment by belek666** [comment]
Uncompressed RGBA 32-bit tgas are only supported. If font file is missing or its format wrong patches wont be loaded.

**Comment by AeroWidescreen** [comment]
@belek666 
Thank you. Those settings still wouldn't work using Photoshop, so I had to use GIMP to export it again as a tga (origin: top left) and that worked fine.

_Note: when you export the tga in Photoshop, make sure the alpha channel is called "Alpha", not "Alpha 1", otherwise GIMP won't detect the alpha channel._

Fantastic job, I really can't emphasize that enough! The only issue I noticed was the occasional flicker of some of the letters when navigating the options menu. I would love to see this added to SH2E if that could be fixed.

@Polymega  
Check it out, HD font is a real thing now! We'll have to replace all of those letters, because I don't think upscaling is going to work for this. Maybe we could split the work somehow. At 4400x9600, Times New Roman at 64pts seemed to be a good start.

**Comment by Polymega** [comment]
Sorry @belek666 for the delay. I saw your post on this and am very excited to try this out myself! Great work all around with this!! 

And thanks to @AeroWidescreen for getting a head start on playing with this! 

> Maybe we could split the work somehow. Times New Roman at 64pts seemed to be a good start.

Absolutely, I'd be glad to help.

And I got you, my friend. Here's Palatino Linotype and TeX Gyre Pagella (for Windows):
[pala.zip](https://github.com/belek666/fontsh234/files/2757043/pala.zip)
[texgyrepagella-regular.zip](https://github.com/belek666/fontsh234/files/2757055/texgyrepagella-regular.zip)

I use TeX Gyre Pagella on my videos [as seen here](https://youtu.be/6v1USVhtfjQ?t=18) and is an _extremely close_ approximation to the font used in the game. (Palatino Linotype is probably the same.) You'll just need to edit the type facing a little to make it match. Here are the settings I used for it in the After Effects videos: 

![image](https://user-images.githubusercontent.com/27395260/51141311-d1d11b00-1816-11e9-8ba4-666ed2d49932.png)

Just apply these settings to the font in whatever software you use (you can apply these same adjustments in Photoshop as well, for example), then scale it all accordingly. Don't forget the drop shadow (unless the game dynamically adds that in?)

I'm going to tag @elishacloud on this just to ping it on his radar. :)

Great work again, @belek666 !

**Comment by Polymega** [comment]
Here's a working file/early pass of the top-most line re-done. I haven't exported/converted anything with it yet but if you'd like a working file for your records (it's done in Adobe Illustrator):
http://www.igotaletter.com/temp/sh2pc/SH2_PC_-_HD_Fonts_001.zip

> The only issue I noticed was the occasional flicker of some of the letters when navigating the options menu.

I experienced that too and missing text at the bottom of the save screen (when choosing a file to save/load from) and the floating, enlarged text on the save screen.

**Comment by AeroWidescreen** [comment]
>And I got you, my friend. Here's Palatino Linotype and TeX Gyre Pagella (for Windows):

Thanks! I was always curious what font you used for your videos.

> Here's a working file/early pass of the top-most line re-done. I haven't exported/converted anything with it yet but if you'd like a working file for your records (it's done in Adobe Illustrator):

Looks nice, but I removed the bold and it looks much better now in my opinion. I also changed the color mode from CMYK to RGB and fixed some spacing and sizing issues.

https://mega.nz/#!tChzgYqD!S8qJdQH2kkrVyHJFRwt58d6Hih6AO7AfIUqbV05H-dw

![HD Font](https://i.imgur.com/dO60UfE.png)

**Comment by Polymega** [comment]
> Looks nice, but I removed the bold and it looks much better now in my opinion

Beautiful and I agree. I wasn't sure if it used bold or not when "tracing" over the original letters. 

So, uh, can you teach me how to work on/implement the new TGA file? I did the first line, saved it out as 32 bit RGBA TGA, re-exported through GIMP (using top-left), but couldn't get it to work. Do I need to hex extract a header from the original TGA file? 

> I also changed the color mode from CMYK to RGB 

Definitely. I'm glad you caught that as I didn't warn about that. Illustrator works in CMYK but it's also great to use as a working template for text/font work vs a raster program like Photoshop.

**Comment by AeroWidescreen** [comment]
> So, uh, can you teach me how to work on/implement the new TGA file? I did the first line, saved it out as 32 bit RGBA TGA, re-exported through GIMP (using top-left), but couldn't get it to work. Do I need to hex extract a header from the original TGA file?

1. Load the .ai document in Photoshop. Change the image size to 4400x9600 when you import.
2. Create the alpha channel. You can duplicate the red, green, or blue channel and rename it as "Alpha"
_Optional: Select the RGB channel and color the entire image solid white. This will give you a cleaner transparency. Remember the tree texture? Same idea._
3. Save as TGA, 32 bits, no compression.
4. Load the  TGA image in GIMP. Export as TGA, origin: top left, no compression.

**Comment by Polymega** [comment]
Thanks, Aero_. The only thing I did wrong/didn't catch was that compression was enabled for the GIMP export. D'oh.

Quick note: Capital W has the serif on the top-left most portion of the letter cut-off in-game. I squished that letter in slightly and typed out the **second** line of characters in the TGA file now: 
http://www.igotaletter.com/temp/sh2pc/SH2_PC_-_HD_Fonts_002.zip

Also, make a backup of the following file: 
`\sh2e\etc\message\stage_observation_msg_e.ms`

Then, download and place this file in that same place:
[stage_observation_msg_e.zip](https://github.com/belek666/fontsh234/files/2757754/stage_observation_msg_e.zip)

Grab the map out of your car then re-examine your car:
![image](https://user-images.githubusercontent.com/27395260/51154564-3d7cad80-1842-11e9-993e-14790b645644.png)

**Comment by AeroWidescreen** [comment]
> We can see the serif is also cut on the captial T and the bottom-left of capital J as well. May I give you the honors of tweaking and passing back my way? I just don't want to double-dip and do the same work over on each other.

Sure, but the archive you uploaded gives me an error. I can't use the illustrator document.

**Comment by AeroWidescreen** [comment]
Nevermind, it fixed itself. Maybe I tried downloading it while it was still uploading to your server.

**Comment by Polymega** [comment]
Yeah do me a favor and download it _one more time_ (as of now). I went ahead and fixed the capital T and J since I already had it opened. I also did the smaller version of the capital alphabet (near the middle of the TGA file) only because I was curious if that's what the main menu for the Director's Cut version uses (it does).

**Comment by AeroWidescreen** [comment]
> We can see the serif is also cut on the captial T and the bottom-left of capital J as well. May I give you the honors of tweaking and passing back my way? I just don't want to double-dip and do the same work over on each other.

I tested the tga file you provided, and "T" and "J" both look fine. No adjustments made.

![example](https://i.imgur.com/7vRPiV0.png)

**Comment by AeroWidescreen** [comment]
I finished the first and second line of the smaller characters and made a few corrections to the larger characters. 

[Download](https://mega.nz/#!xehEhATa!xoJ4bvnA_tQFZxga6Wq-EIJnAlxzZFQqGMJyXO63ybM)
![Inventory](https://i.imgur.com/b7b5Imf.png)

I don't know what your plan is, but I don't think we really need to replace _everything_, like the Wingdings or whatever you call them. I've never seen any of those used before, and I don't know what purpose they would ever have. We could just leave those blank.

**Comment by belek666** [comment]
> The only issue I noticed was the occasional flicker of some of the letters when navigating the options menu.
> I experienced that too and missing text at the bottom of the save screen (when choosing a file to save/load from) and the floating, enlarged text on the save screen.

Never happened to me. Which version o the game executable do you use? Can you send me it to test?
Width of Latin chars (index 0-255) can be adjusted if there is some difference. We could use also higher resolution if we remove unused chars - is 4400x9600 enough?

**Comment by Polymega** [comment]
Here is a video showing the issues on the save screen and Options menu:
https://youtu.be/S4pRf2AU194

> Which version o the game executable do you use? Can you send me it to test?

Sure thing. Here are all three "No CD" versions of the executable: [Original No CD Executables.zip](https://github.com/belek666/fontsh234/files/2760260/_Original.No.CD.Executables.zip)
1. Version 1.0 (North American retail copy)
2. Version 1.1 (after applying Konami's official sound patch to 1.0)
3. Director's Cut (European retail copy).

> is 4400x9600 enough?

It looks really good to me. What do you think @belek666 and @AeroWidescreen ? Is that resolution good or would you want to go up even more?

**Comment by Polymega** [comment]
> We could use also higher resolution if we remove unused chars

Maybe also worth mentioning: **NO** PC version has Japanese as a language option. So you could remove all Japanese characters from the TGA image and it should be fine.

**Comment by AeroWidescreen** [comment]
> We could use also higher resolution if we remove unused chars - is 4400x9600 enough?
> It looks really good to me. What do you think? Is that resolution good or would you want to go up even more?

I agree, it looks good to me. I know this sounds odd, but I fear going with a higher res might make the font too sharp compared to the rest of the game. I would like to see the unused Japanese characters removed, like Polymega suggested, since that could reduce file size by a significant amount.

The good thing is we're doing all of this in vector, so increasing the resolution is not a problem (from a texture standpoint) if we ever change our minds on this.

**Comment by Polymega** [comment]
@belek666 , if it's possible, the areas in red should be the only segments we'd need to keep. Could this be done? 

![sh2-pc---hd-fonts-003](https://user-images.githubusercontent.com/27395260/51209134-859cde00-18dd-11e9-867a-3aedbe2b96bf.jpg)

And could the areas in red by consolidated together to look more like this (to save on file size)?

![sh2-pc---hd-fonts-004](https://user-images.githubusercontent.com/27395260/51215217-44f99080-18ee-11e9-9a40-e73152215584.jpg)

**Comment by Polymega** [comment]
> I know this sounds odd, but I fear going with a higher res might make the font too sharp compared to the rest of the game. 

Definitely agree with that.

@AeroWidescreen 
I've continued our work on this and now 4 (+ 1/3 of another) lines are done for the top and middle portions. I went ahead and did some of the wing ding characters just because it was easy enough to do (that, and I didn't want to leave a middle-segment of a line incomplete due to OCD). 

I think that should cover our bases for any conceivable characters that would be used for the game? You may want to double-check my work for letter and line spacings. For example: I had to move the **Ó** (and other O letters with special markings) up higher than the others for them to be properly aligned in-game. 

http://www.igotaletter.com/temp/sh2pc/SH2_PC_-_HD_Fonts_003.zip

Here are some additional fonts that I used, in case you don't have them: 
http://www.igotaletter.com/temp/sh2pc/extra_fonts.zip

**Comment by Adam-Saeed** [comment]
Sorry to interrupt you guys, but how can I get the font map as you did?
(my font is made for a different language)

**Comment by AeroWidescreen** [comment]
@Polymega 
> I think that should cover our bases for any conceivable characters that would be used for the game? 

Seems so. Nice job.

> You may want to double-check my work for letter and line spacings. For example: I had to move the Ó (and other O letters with special markings) up higher than the others for them to be properly aligned in-game.

https://mega.nz/#!1LoGXAZB!mUXZE7sENeRe7Cg6-sdZAqVX4jbPDx6gkzWu4QSdG2Q

I noticed some inconsistent spacing (kerning) issues in-game, but the original font has the same problem. It's not something we can fix via texture.

@Adam-Saeed 

It should be in the download provided by belek666. It's called "font000.tga".
https://github.com/belek666/fontsh234/files/2752256/Release.zip

**Comment by Adam-Saeed** [comment]
I meant how to extract the font into tga file

**Comment by Polymega** [comment]
TGA files are flat, 2D _images_. You can't extract text out of them. Aero_ and I have been placing _new_ text on top of the TGA image "by hand," using the TGA image as a template to know where to place the new characters. Essentially you would have to do the same.

**Comment by Adam-Saeed** [comment]
Sorry, my English isn’t that good.
I want to get the font out of the exe file

**Comment by Polymega** [comment]
Oh, I see. Sorry about the confusion. I wouldn't know how to do that. belek666 may know and @lakeviewhotel recently did just this when making a Chinese translation patch for the game.

**Comment by belek666** [comment]
@Polymega 
> if it's possible, the areas in red should be the only segments we'd need to keep. Could this be done?

Yes, number of chars in column/row is adjustable and I think it's value should be configurable in settings. Here is new version with fixed flickering letters, added loading width data from external file and modified to use 100x14 chars texture. 
[Release.zip](https://github.com/belek666/fontsh234/files/2765781/Release.zip)

@Adam-Saeed 
I've modified sh234 font extractor to uncompress all chars to single tga image including empty chars.

**Comment by Polymega** [comment]
Thank you very much, belek666! 

Would you mind providing a new 100x14 character set TGA? I've reduced/resized our working file but the texture is not loading in-game for me. I believe this may be because I don't know what to proportionally scale the new image dimensions as?

**Comment by belek666** [comment]
[Silent Hill 2.zip](https://github.com/belek666/fontsh234/files/2765985/Silent.Hill.2.zip)
I've also added d3d8.ini file with custom font option enabled. I forget to include it before. Single char is 22x32.

**Comment by Polymega** [comment]
This is _really nice_, belek666! We've reduced the texture size to 15 MB uncompressed which is 10x smaller than the original (at around 160 MB). 

Before, I noticed a slight freeze (just a few frames) whenever subtitles would start on a cutscene or FMV. With this new version (and the smaller TGA file now) I haven't really noticed any momentary freezes yet. Well done! 

@AeroWidescreen here are the working texture files: 
- http://www.igotaletter.com/temp/sh2pc/SH2_PC_-_HD_Fonts_004.zip

Here is belek666's latest build:
- https://github.com/belek666/fontsh234/files/2765781/Release.zip
- https://github.com/belek666/fontsh234/files/2765985/Silent.Hill.2.zip

Here are the additional files from within belek666's newest build: 
- `d3d8.ini` - With the line `UseCustomFonts = 1` within the file.
- `fontwdata.bin` - Contains font width data for the custom font.

> Here is new version with fixed flickering letters

Works great! The only thing I noticed that is still missing is the enlarged, "floating" text whenever you're in the save screen menu. 

![sh2pc 2019-01-16 16-31-30](https://user-images.githubusercontent.com/27395260/51279857-32459100-19ac-11e9-9719-60c10eaac278.png)
![sh2pc 2019-01-16 16-33-17](https://user-images.githubusercontent.com/27395260/51279949-73d63c00-19ac-11e9-94fe-7cb246944ea1.png)

Is that also possible to restore? If not, I think the save screen still looks fine without it.

**Comment by AeroWidescreen** [comment]
@Polymega 
Thanks! I still can't believe this is a thing now. Just a year ago it was nothing more than a wish. A very welcome surprise from belek! 👍 

> Works great! The only thing I noticed that is still missing is the enlarged, "floating" text whenever you're in the save screen menu.

Yeah, it's arguably an upgrade lol, but it wouldn't hurt to investigate what's causing that.

**Comment by nipkownix** [comment]
This is just amazing. Thank you, guys! I love this community!

**Comment by Polymega** [comment]
>  I still can't believe this is a thing now. Just a year ago it was nothing more than a wish. A very welcome surprise from belek! 

Absolutely! And now it's only a matter of time until someone sees everything that's being done for the game and says, "Wait a minute! I know how to implement soft shadows!"

> Yeah, it's arguably an upgrade lol, but it wouldn't hurt to investigate what's causing that.

I actually agree with you on this, haha. But I've already received flak for adding a power cord to the game so I'd imagine there'd be some comments if this isn't at least looked in to.

**Comment by Adam-Saeed** [comment]
@belek666 what's the command to uncompress all chars in sh234?

**Comment by belek666** [comment]
@Polymega @AeroWidescreen 
I've brought back that text on the save/load screen. It was just typo in code :) I've also added font setting into ini file. Here is latest build:
[Release.zip](https://github.com/belek666/fontsh234/files/2773697/Release.zip)
If everything is ok I could make pull request to main repo. I also would like to ask you about one request. Could you make additional hd font for Polish translation of sh2? Chars that should be added:  ą ć ę ł ń ó ś ź ż and capital version: Ą Ć Ę Ł Ń Ó Ś Ź Ż. Here is my old font that I created before with width data.
[plfonts.zip](https://github.com/belek666/fontsh234/files/2773741/plfonts.zip)
I will be grateful :)
@Adam-Saeed  
This version is not public yet. Why do you need to extract all chars? Full texture was posted here already.

**Comment by Adam-Saeed** [comment]
My old font is made for a different language

**Comment by Polymega** [comment]
> I've brought back that text on the save/load screen. It was just typo in code

Thanks again, @belek666 !

> If everything is ok I could make pull request to main repo.

May I ask for two more requests? After these requests, I believe we are good to go! 

1. Can you please ~~disable~~ **make an option in the .ini file to disable** the enlarged, floating text on the save screen now? After seeing it activated, it is way too visually distracting to keep it enabled. 
2. Can the additional, external files be moved to `\sh2e\font\` ? So it would be: 
```
\KONAMI\Silent Hill 2\d3d8.dll
\KONAMI\Silent Hill 2\d3d8.ini
\KONAMI\Silent Hill 2\sh2e\font\fontwdata.bin
\KONAMI\Silent Hill 2\sh2e\font\font000.tga
```

For the Enhanced Edition project, we try to keep every modded (or added) file inside the `sh2e` folder. This keeps all the files in one location and makes things easier for other people when installing the fixes.

> I also would like to ask you about one request. Could you make additional hd font for Polish translation of sh2?

Of course! I would be happy to do this and it is the least I can do for all your wonderful work. :) 

> Chars that should be added: ą ć ę ł ń ó ś ź ż and capital version: Ą Ć Ę Ł Ń Ó Ś Ź Ż

~~Would you like me to add the additional characters at the end (areas in red)? Or would you like me to replace pre-existing characters? If so, which ones should I replace?~~

Nevermind, I see the additional Polish characters scattered through the image file. I will have this to you soon.

**Comment by Polymega** [comment]
Hi @belek666 , 

Here is the Polish version of the HD fonts. Please check it over and make sure I have all the unique characters accounted for: 
http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Polish_Fonts_002.zip

Also included is the Adobe Illustrator (`.ai`) file. If you have a copy of Illustrator, you can open this file if you ever decide to change the characters in the future.

**Comment by AeroWidescreen** [comment]
@belek666 
> I've brought back that text on the save/load screen. It was just typo in code :) I've also added font setting into ini file. Here is latest build:

Fantastic! There's nothing more I can say really, you did it! I'm looking forward to the pull request.

> Could you make additional hd font for Polish translation of sh2? Chars that should be added: ą ć ę ł ń ó ś ź ż and capital version: Ą Ć Ę Ł Ń Ó Ś Ź Ż. Here is my old font that I created before with width data.

Absolutely. I would do it myself, but it looks like Polymega has got you covered.

@Polymega 
> 1. Can you please disable the enlarged, floating text on the save screen now? After seeing it activated, it is way too visually distracting to keep it enabled.

If this is done then I would like to see it as an option, because you know someone is going to complain about it eventually. 😛

**Comment by Polymega** [comment]
> If this is done then I would like to see it as an option, because you know someone is going to complain about it eventually. stuck_out_tongue

Good point. I'd say 25% of YouTube comments on my latest YouTube SH2:EE update video were people having issues with a power cord. So I can also see that being a point of contention. :roll_eyes:

**Comment by Polymega** [comment]
> If this is done then I would like to see it as an option, because you know someone is going to complain about it eventually.

Good point. I'd say 25% of YouTube comments on my latest SH2:EE update video were people having issues with a power cord. So I can also see that being a point of contention. :roll_eyes:

@AeroWidescreen 
I adjusted the special A, E, I, O, U characters as they were all slightly misaligned vertically, and I also made a Photoshop template for the final image so we can preserve this warning for any future edits we may do:
http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Fonts_005.zip

Now, if someone were to open the .tga file in a program like Photoshop they'd see this: 

![sh2-pc---hd-fonts](https://user-images.githubusercontent.com/27395260/51419024-4ed0fd00-1b55-11e9-9688-d80b1cb150f1.jpg)

**Comment by Polymega** [comment]
@AeroWidescreen @belek666 
I noticed just about all the special A, E, I, O, U, Y characters (such as Á, Ê, Ö, etc) were misaligned vertically by a pixel or two. I went back and re-adjusted all these characters and it's looking even better now. Here are the current working files: 

**Aero_:** http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Fonts_005.zip
**Belek666:** http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Polish_Fonts_002.zip

^ I've updated my recent, previous posts with these new links.

@belek666 
- If I may suggest, I would recommend having the enlarged, floating save menu text **disabled by default** in the `.ini` file. 
- I would also recommend changing `CustomFontCharWidth =` from `22` to `20` **by default** in the `.ini`  file. This makes the width of the letters more accurate to the default version: 

![font2](https://user-images.githubusercontent.com/27395260/51421318-92823180-1b6a-11e9-8227-ab9a96e565d3.gif)

**Comment by belek666** [comment]
@Polymega @AeroWidescreen 
Thank you.  New fonts are great!

>     Can you please disable make an option in the .ini file to disable the enlarged, floating text on the save screen now? After seeing it activated, it is way too visually distracting to keep it enabled.

Done. I'm not sure if this may affects some other text in game.

>     Can the additional, external files be moved to \sh2e\font\
Done too. If font file is missing patches wont be loaded. File "fontwdata.bin" is optional, for custom fonts.

> I would also recommend changing CustomFontCharWidth = from 22 to 20 by default in the .ini file. This makes the width of the letters more accurate to the default version:

Ok, I've to move Polish font by 3 px to right to get the same result.
[Release.zip](https://github.com/belek666/fontsh234/files/2775523/Release.zip)

@Adam-Saeed 
[sh234font.zip](https://github.com/belek666/fontsh234/files/2775530/sh234font.zip)
Normal and small fonts are extracted separately. Then manually joined. Example commands:

`sh234font sh2pc.exe n b 100 75 nfont.tga`
With this you get all normal chars extracted. 

`sh234font sh2pc.exe s b 100 75 sfont.tga`
With this you get all small chars extracted. 

100 is number of chars in column, 75 is number of chars in row (we are currently using 7 (14 in ini file for joined normal and small fonts).

**Comment by Polymega** [comment]
This is fantastic, @belek666 ! I'd say everything is accounted for and is good to be pushed for a pull request! Well done!! There are going to be _so many people_ who are going to love your fix! 

I have a few more questions for you. [Please see this page.](http://enhanced.townofsilenthill.com/SH2/credit.htm) May I add your name/info to this page? If so, can I please get the following information: 

1. What name would you like to be credited by? Belek666 or something different? 
2. Do you have a website/contact/donation link you would like me to include? (These are not required)
3. Would you consider writing a short paragraph (it doesn't have to be long... just a few sentences) about yourself? Perhaps about what got you into the Silent Hill series or what interested you in modding the games? 

> Ok, I've to move Polish font by 3 px to right to get the same result.

Here you go friend; I moved the characters 3 pixels to the right: 
http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Polish_Fonts_003.zip

**Comment by belek666** [comment]
> What name would you like to be credited by? Belek666 or something different?

Belek666 should be good :)

> Do you have a website/contact/donation link you would like me to include? (These are not required)

email: belek666@onet.eu
website: https://github.com/belek666
donation: https://www.paypal.me/ppieniak

> Would you consider writing a short paragraph (it doesn't have to be long... just a few sentences) about yourself? Perhaps about what got you into the Silent Hill series or what interested you in modding the games?

I'm hobbyist C/C++ programmer. My main interest was Playstation 2 homebrew scene. I've made/ported some applications to this console. Silent Hill on PlayStation was my first survival horror game that I'd played and it was scary experience but I loved it and whole series. I'm also interested in modding games and I'm involved in Polish fan translation of Silent Hill 2.

> Here you go friend; I moved the characters 3 pixels to the right:
> http://www.igotaletter.com/temp/sh2pc/SH2_PC_HD_Polish_Fonts_003.zip

Thanks :)

**Comment by Polymega** [comment]
Perfect! Thank you Belek666. 

When Elisha releases the next update to the SH2 Enhancements mod (which will contain your wonderful font mod) I will then update the Installation Guide to provide details of your mod on the [Config page](http://enhanced.townofsilenthill.com/SH2/config.htm) and include your name/links/bio in the [Credits page](http://enhanced.townofsilenthill.com/SH2/credit.htm). :)

Also, I read over your bio, and, would you possibly know how to fix another issue we're having with the game? Here is the thread/info: 
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/2

This seems to be a fairly complicated fix. It turns out that certain functions within light regions simply doesn't exist in the PC version for a few areas. Because of this, James does not smoothly "fade out" from these light sources but instead instantly becomes darker at the end of the light zones. 

Bigmanjapan has discovered that the issues are from missing functions for these addresses seen here: 
https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/2#issuecomment-391459448

We were in touch with another PS2 modder named Nekorun, and he suggested possibly transposing the lighting data for these areas from the PS2 version to the PC version using LUA scripting or something similar. (And modify the address regions appropriately so the PC version can understand it.) Unfortunately, Nekorun isn't really interested in helping us so we're stuck on how to resolve this issue. 

Any insight is welcome if you've done anything this intricate before. 
Thanks again, Belek666!

**Comment by belek666** [comment]
@Polymega 
I've taken a look at the problem and possibly found some workaround. Not sure if it's correct solution. Here is CE table (for sh2pc English version) I'm using:
[sh2pc.zip](https://github.com/belek666/fontsh234/files/2800227/sh2pc.zip)
Change 'SomeType' value to '2'. This value is related to some light calculation and the difference between type '2' and '3' is that '3' make some additional calculation and probably this function is bugged. For now I don't have idea what's wrong. Maybe patching function to use type '2' instead '3' is enough to fix the problem.

**Comment by Polymega** [comment]
Thank you again for all your hard work, Belek666. I'll close this thread as the original request of an HD font mod has be successfully created.

If you'd like, I've made a thread about restoring the specularity for the game [found here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/73) if you'd like to continue the discussion.
