### ISSUE TITLE
Adjust letter spacing

### ISSUE THREAD

**Issue by Adam-Saeed** [belek666/fontsh234#3]
Is there's a way to adjust the letter spacing?
![image](https://user-images.githubusercontent.com/43554017/47118792-27764580-d271-11e8-8c75-a4c5c6b73613.png)
Although I don't think it has anything to do with the font itself, I might be wrong.
and it may be a small space but it's critical for languages that require connecting letters.

**Comment by belek666** [comment]
Hi
From what I found there is no data related to letter spacing in the fonts. I think that there might be some global value somewhere in the exec file. What I would do is estimate size of spacing and search that value in exec using hexeditor, change it and check in game.
