### ISSUE TITLE
SH3 & SH4 font extraction

### ISSUE THREAD

**Issue by Adam-Saeed** [belek666/fontsh234#4]
Hey, thank you for this great tool.

I managed to make my font for SH2 and it turned out great, but I had troubles with the later games. I can't find any indication of a font file in the game's files and for SH4 I did find Fontdata.bin but it doesn't give anything.

I must've done something wrong here but can't figure it out.

**Comment by belek666** [comment]
Hi
SH3 has font files named 'fontdata_x.bin'. They are packed into 'msg.arc' file. PS2 version also has the same file but it uses one embedded in executable file (PAL version, not sure about NTSC). SH4 has 'fontdata.bin' exactly the same as PS2 version. Extraction of single char should work. Which command did you tried?

**Comment by Adam-Saeed** [comment]
I'm modding the PC version of the games. I don't remember seeing a tool for unpacking sh3 msg.arc, is there a way to do so?
For SH4 I was importing instead of exporting, it worked after fixing it, but there's some kind of corruption under every character. The command I used: 
fontsh234 fontdata.bin n e 33 Capital.Letter.A.tga
![image](https://user-images.githubusercontent.com/43554017/74616682-5a1ca080-513a-11ea-8bc4-bc0266a39b2d.png)

**Comment by belek666** [comment]
Try new release: [https://github.com/belek666/fontsh234/releases](https://github.com/belek666/fontsh234/releases)
You can use my old programs to unpack/pack sh3 arc files: 
[sh3arc.zip](https://github.com/belek666/fontsh234/files/4214514/sh3arc.zip)
To unpack drop *.arc file onto 'arc_unp.exe', file 'arc.arc' need to be in the same folder as archive. Files will be unpacked to 'data' folder. To pack files back drop the same *.arc file onto 'arc_pck.exe'. If a file exist in 'data' folder then it will be placed in archive other ways original file from archive. The new *.arc_new file will be created.

**Comment by Adam-Saeed** [comment]
sh3 extracted the files successfully.
sh4 still the same, all the characters are squished and has some kind of corruption.

**Comment by belek666** [comment]
Try with 'fontdata_kr.bin', this is what game mainly use, not sure about others font files.

**Comment by Adam-Saeed** [comment]
Thank you very much, it worked.
Now I can respond to the requests for translating the other games xD
Do you have Paypal? I'm really grateful for your help

**Comment by belek666** [comment]
I'm glad I could help. Paypal: [link](https://www.paypal.com/paypalme2/ppieniak)
