### ISSUE TITLE
problem with your fontsh234 program

### ISSUE THREAD

**Issue by kiminru** [belek666/fontsh234#6]
![font_normal 100 75](https://user-images.githubusercontent.com/84241069/170286300-5beedd72-5f62-4843-bc01-48b6506b7032.jpg)
can be extracted up to a maximum of 'fontsh234.exe sh2pc.exe n b 100 75 font_normal.tga', that is, '100 75'.

![font_normal-100-6](https://user-images.githubusercontent.com/84241069/170286403-4fa348f0-9523-4091-a765-1b67f34ceb66.jpg)
import, can only do it up to 'fontsh234.exe sh2pc.exe n b 100 6 font_normal.tga', that is, '100 6'.

![2](https://user-images.githubusercontent.com/84241069/170286475-1ec91c5e-0029-42ee-800b-933769f2e18d.png)
problem is that only 10% of the Korean language can be printed

Hello, we are contacting you because of a problem with your fontsh234 program.

There is a Korean language patch for the PC version of Silent Hill 2.
First of all, in the case of Silent Hill 2, there is no Korean version for PS2, XBOX, and PC versions at all. 
So, Japanese and Chinese font were replaced with Korean font, and fontsh234 program can be extracted up to a maximum of 'fontsh234.exe sh2pc.exe n b 100 75 font_normal.tga', that is, '100 75'.

But import, can only do it up to 'fontsh234.exe sh2pc.exe n b 100 6 font_normal.tga', that is, '100 6'.
This is a problem for both Normal and Small fonts.

I have attached the font photos of '100 75' and '100 6' to the sent file.
The problem is that only 10% of the Korean language can be printed.
Is it possible to improve it so that it can be imported up to 100 75?

South Korea is currently preparing for a Korean port of PS2 Silent Hill 2, but no one has been successful so far. 
That's why I really need your help!

**Comment by belek666** [comment]
Hi
For pc version I'm recommending using this modification http://www.enhanced.townofsilenthill.com/SH2/ 
With this mod You can use custom files as games fonts with higher resolution and specify its configuration. About problem with fontsh234 it's related to limited space for fonts inside games exe file. There are no checks for that in fontsh234 so the safest way would be to first delete all unneeded characters (blacking on bitmap or using program option) to make free space and then adding new.  Also 'bitmap' option may be causing problems as it's not well tested.

**Comment by kiminru** [comment]
The PC version has already been resolved, so the purpose is to port the language patch of the PS2 version.

for example
![1](https://user-images.githubusercontent.com/84241069/170823194-2174a55b-f8b5-42bf-aa8b-082e062c6095.jpg)
This is the font used for the PC version Korean language patch.

![2](https://user-images.githubusercontent.com/84241069/170823233-c191b9b8-1b6a-4b14-bae1-070087a45b2b.png)
This is an example file. (I just painted black with a paint program. This is just an example.)

![KOR_table](https://user-images.githubusercontent.com/84241069/170823291-0914c4c1-e2c3-4f19-95c4-9d7f0268dfa3.png)

Even if I do this, I don't think it's possible to insert a font.

In case you don't know, we provide a font table.
https://drive.google.com/file/d/1JQV_naozlzOXrulOQ7L1Gkowhz5FhXxf/view?usp=sharing

This is a table that includes everything from English to special characters, Japanese, and Chinese characters. I am providing this file in case it helps.

**Comment by belek666** [comment]
Hi
I updated app to work better with bitmaps. Solution for your problem would be:
- extract fonts to bitmap `fontsh234 sh2pc.exe n b 100 40 normal.tga` and  `fontsh234 sh2pc.exe s b 100 40 small.tga`
- then edit tga to delete (paint it black ;)) chars after Korean to make space, remember to save edited tgas without rle compresion and origin Top left. In gimp would be -> Export as... -> Select file type: tga -> uncheck rle, select origin Top left
-  insert edited tgas with  `fontsh234 sh2pc.exe n w 100 40 normal.tga` and  `fontsh234 sh2pc.exe s w 100 40 small.tga`

**Comment by kiminru** [comment]
> Hi I updated app to work better with bitmaps. Solution for your problem would be:
> 
> * extract fonts to bitmap `fontsh234 sh2pc.exe n b 100 40 normal.tga` and  `fontsh234 sh2pc.exe s b 100 40 small.tga`
> * then edit tga to delete (paint it black ;)) chars after Korean to make space, remember to save edited tgas without rle compresion and origin Top left. In gimp would be -> Export as... -> Select file type: tga -> uncheck rle, select origin Top left
> * insert edited tgas with  `fontsh234 sh2pc.exe n w 100 40 normal.tga` and  `fontsh234 sh2pc.exe s w 100 40 small.tga`

Thank you so much! I just got this reply as soon as I woke up! 
I have to go to work right away, so I can't test it right now, so I'll test it right after work, thank you so much! :)
Thank you so much for making this improvement even though you are busy, 
all I can say is thank you very much, thank you so much!

**Comment by kiminru** [comment]
[sh2pc.zip](https://github.com/belek666/fontsh234/files/8831686/sh2pc.zip)
[SLUS_202.zip](https://github.com/belek666/fontsh234/files/8831688/SLUS_202.zip)


"Failed to update character offset."
"Failed to insert character id: 'number'"

Still the same with this error notification
Size to 100 6 can be imported but not after size that.
I extracted and imported up to 100 14 excluding the broken font that comes after Korean, just in case, but I still get an error

The PC version Korean patch exe file (no virus) and the original PS2 file are attached together.

**Comment by belek666** [comment]
Fixed some bugs and now I was able to insert fonts. I first inserted bitmap with deleted unneeded chars to make space and then new ones. If program returns negative size like this `Wrong char parameters: offset: 97016 size: -23820 page 0
         Failed to insert char id: 1401` it means that there is not enough space.

[SLUS_202.zip](https://github.com/belek666/fontsh234/files/8853901/SLUS_202.zip)

Check if chars are displayed correctly in game.

**Comment by kiminru** [comment]
> Fixed some bugs and now I was able to insert fonts. I first inserted bitmap with deleted unneeded chars to make space and then new ones. If program returns negative size like this `Wrong char parameters: offset: 97016 size: -23820 page 0 Failed to insert char id: 1401` it means that there is not enough space.
> 
> [SLUS_202.zip](https://github.com/belek666/fontsh234/files/8853901/SLUS_202.zip)
> 
> Check if chars are displayed correctly in game.

Thank you! Everything is printed properly in Korean! 
You are a great and talented developer! Thank you very much! 
Silent Hill 2 language patch for PS2, which was impossible in Korea, finally succeeded for the first time thanks to you
thank you very much!

**Comment by kiminru** [comment]
![1](https://user-images.githubusercontent.com/84241069/172563875-be5a6e4f-8f28-481b-91cf-5abd4fff10ea.png)
![2](https://user-images.githubusercontent.com/84241069/172563887-f22213c9-6a96-4b56-b349-d0173a60ef3a.png)
![3](https://user-images.githubusercontent.com/84241069/172563901-b2cfa9d0-6b01-411e-9d3b-b402318db55d.png)
![4](https://user-images.githubusercontent.com/84241069/172563918-0ecd307d-e798-45b0-a8e1-af0e2103cb53.png)

printed in Korean! Thank you very much! 
I wrote your nickname(belek666) on our Korean community site. 
Thanks to you, many people are feeling grateful. :)
