### ISSUE TITLE
Full font sheet support with EE project

### ISSUE THREAD

**Issue by Polymega** [belek666/fontsh234#8]
Hi @belek666,

May I summon you from your slumber to help us with adding full font sheet support for the project?

If you remember when we first worked on the HD font sheet, [we excluded the Japanese characters to save on file size](https://github.com/belek666/fontsh234/issues/2#issuecomment-454547238). Since then, a Japanese fan has taught us how to properly restore the Japanese language for SH2 PC. We very much would like to include the Japanese language back into the game and, in doing so, would also like to offer an HD character set for the language.

Thanks to @toraMeeKay in submitting the Japanese characters, we have made a new `font000.tga` that includes the entire font sheet ([50% JPG preview.](https://user-images.githubusercontent.com/27395260/186553032-82902734-f79c-430d-b23d-7b3f50b686e5.jpg)). 

The TGA is 9.2 MB compressed and 160 MB uncompressed: [font000.zip](https://github.com/belek666/fontsh234/files/9428894/font000.zip)
DDS version: [font000.zip](https://github.com/belek666/fontsh234/files/9440265/font000.zip)

May I ask if you would restore full font sheet functionality with the EE project? This would likely also involve modifying how the `fontwdata.bin` file works.

Thank you so much friend

**Comment by belek666** [comment]
HI @Polymega 

If I remember correctly You only need to change font settings in config to:

```
; Number of chars in column on font texture. Default value 100. Do not change.
CustomFontCol = 100

; Number of chars in row on font texture. Default value 14. Do not change.
CustomFontRow = 150
```

About `fontwdata.bin` it is only for first 224 glyphs and rest have fixed width - default game implementation. Of course it could be patched if needed ;)

Best regards

**Comment by Polymega** [comment]
Ah, you're a smart man, Belek! Thank you.

From using a full font sheet now, this file is 160 MB. Is there any possibility of using a different format to reduce its size? DXT3, DXT5, or TGA with compression enabled?

DXT3 & DXT5: ~40 MB
TGA (Compress RLE): ~55 MB

**Comment by belek666** [comment]
You mean just reduce file size? Isn't there any visible delays when using such a big texture? Maybe we could use directx api to use dxt compressed textures or some external library (png support?). It should be quite easy to do this. I will look at this later. 

Png support added. First it looks for tga file then for png
[d3d8.zip](https://github.com/belek666/fontsh234/files/9434376/d3d8.zip)

**Comment by Polymega** [comment]
You smart cookie, you! In PNG format, the file jumps way down to ~10 MB... even less than the current public release font sheet.

However, I am experiencing severe performance issues with the game and noticed the noise filter is negatively affected by this change:

![Screenshot 2022-08-26 19-52-38](https://user-images.githubusercontent.com/27395260/187008389-94f527a8-58da-4d80-83f3-0627ce3481ff.png)

**Comment by Polymega** [comment]
Here is a test `font000.png` file (subject to change): [font000.zip](https://github.com/belek666/fontsh234/files/9437054/font000.zip)

**Comment by Polymega** [comment]
If PNG proves to be too inefficient when used in the game, then it's no problem to keep the font sheet in TGA format. It is better to have a large file size that is good in performance vs. a small file size that is poor in performance.

Please note I have not yet done any extensive performance tests using the new 4400x9600 font sheet (for PNG or TGA). Sadly, I do know that this new, massive resolution for the font sheet will no longer work for older computers with integrated graphics processors:

![Screenshot 2022-08-27 20-37-33](https://user-images.githubusercontent.com/27395260/187052815-41446249-d459-45eb-bb04-138b5aa89067.png)

^ This is from my older Surface Pro 3 laptop. Unfortunately, I don't think much can be done about this if we restore the Japanese language as we're doing. Although, I don't know if this makes sense or would help with loading/performance, but would splitting the font sheet into two help any?

![font000temp](https://user-images.githubusercontent.com/27395260/187052900-90d32332-cb8b-4368-872f-a4fabb0285e4.jpg)

**Comment by belek666** [comment]
Yeah, there is visible lag before first text appear. For performance please check this:
[d3d8.zip](https://github.com/belek666/fontsh234/files/9439758/d3d8.zip)
 
Instead png it uses .dds files with dxt compression.
DXT5 font file:
[font000.zip](https://github.com/belek666/fontsh234/files/9439762/font000.zip)

**Comment by Polymega** [comment]
Nice! Using DXT5 looks to be good. I've done a few tests with and without the font sheet and the performance difference was negligible.

> Png support added. First it looks for tga file then for png

Oh, when this gets pushed to the main project, should we drop TGA support in favor of DDS support only? Keep in mind the default values for `CustomFontCol` and `CustomFontRow` will be changed for the project, which will break the old TGA font sheets by default.

I personally would prefer only having one file format in use to avoid confusion. I would work with people (as I previously done) to convert their font sheets over to DDS that includes the new Japanese characters.

**Comment by Polymega** [comment]
PS - I would like to add your Polish language pack [as a download on the project site](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/579#issuecomment-1218899105) in the future. Can I work with you to make this happen at some point?

**Comment by Polymega** [comment]
You're a pretty amazing person, Belek. Thank you for your continuous strive to make things look/work better for the project.

Before I close this ticket, could you send me a link to the Polish fan translation pack for the game? (I believe you created it?) I'd like to see if we can include this translation pack as a download on the project site.

**Comment by Polymega** [comment]
Hi Belek!

Sorry to keep bugging you, but would you like or not like us to host the Polish translation pack on the project site? If so, may I get a link to the pack? Please let me know either way. And thank you for everything you do!
